Lesson_1_7
AE-BHH/react-todo pull request #8
Opened 2023-11-30 13:38 UTC by AE-BHH

Week 8:
Lesson_1_7
Asynchronous Data
Conditional Rendering
Advanced & Impossible State

2023-11-30 18:23 UTC, JoHeyJo requested changes
Well done implementing everything you've learned in the lesson, it wasn't an easy one. There are a few minor things to address but there is still a pretty big bug lingering from a previous lesson that somehow made it over to this branch. Your form still doesn't submit when you hit 'enter' on your keyboard. Please fix this before merging and moving on. 

Let's get everything sorted out before merging. I'll approve after revisions have been made.

2023-11-30 18:23 UTC, JoHeyJo commented on src/App.js
> +		JSON.parse(localStorage.getItem('savedTodoList') || [])
`JSON.parse(localStorage.getItem('savedTodoList')` is already being applied on mount. Is this necessary?

2023-11-30 18:23 UTC, JoHeyJo commented on src/App.js
> +	useEffect(() => {
This is fantastic! Good job also including error handling!
 Let's clean up all those console logs.

2023-11-30 18:23 UTC, JoHeyJo commented on src/App.js
> +	function removeTodo(id) {
Nicely done implementing `removeTodo`.

2023-12-04 04:42 UTC, AE-BHH commented on src/App.js
> +		JSON.parse(localStorage.getItem('savedTodoList') || [])
I removed this JSON.parse() method from todoList useState.
Thanks for the feedback!

2023-12-04 04:43 UTC, AE-BHH commented on src/App.js
> +	useEffect(() => {
Yes, sure!

2023-12-15 22:22 UTC, merged